# Generated by Django 6.0.1 on 2026-01-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='is_truee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='details',
            field=models.CharField(max_length=255),
        ),
    ]
