# Generated by Django 6.0.1 on 2026-02-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='close_time_friday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='close_time_monday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='close_time_saturday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='close_time_sunday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='close_time_thursday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='close_time_tuesday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='close_time_wednesday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_bike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_car',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_radius',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='late_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='max_books',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='offers_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='offers_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='offers_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='open_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='open_monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='open_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='open_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='open_thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time_friday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time_monday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time_saturday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time_sunday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time_thursday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time_tuesday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time_wednesday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='open_tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='open_wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_methods',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='rental_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
