# Generated by Django 6.0.1 on 2026-02-04 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_store_agree_terms_store_close_time_friday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_book_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('publication_year', models.IntegerField()),
                ('total_copies', models.IntegerField()),
                ('available_copies', models.IntegerField()),
                ('available_sales', models.IntegerField()),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.store')),
            ],
        ),
    ]
