# Generated by Django 6.0.1 on 2026-02-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_add_book_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_book_registration',
            name='available_copies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='add_book_registration',
            name='available_sales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='add_book_registration',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_book_registration',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='add_book_registration',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='add_book_registration',
            name='total_copies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
