# Generated by Django 6.0.1 on 2026-02-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_add_book_registration_available_copies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_book_registration',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.store'),
        ),
    ]
