# Generated by Django 6.0.1 on 2026-02-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_add_book_registration_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(default='fiction', max_length=100)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('total_copies', models.IntegerField(default=0)),
                ('available_copies', models.IntegerField(default=0)),
                ('available_sales', models.IntegerField(default=0)),
                ('rental_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
