# Generated by Django 6.0.1 on 2026-02-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.store'),
        ),
    ]
