# Generated by Django 6.0.1 on 2026-02-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_book_registration',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('rent', 'Rental'), ('buy', 'Purchase'), ('mixed', 'Mixed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('contacted', 'Contacted'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup/Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Declined')], default='pending', max_length=20),
        ),
    ]
